version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    environment: 
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=bd_name
      - DATABASE_USER=kali
      - DATABASE_PASSWORD=kali
    depends_on:
      - db
    networks:
      - custom_network 

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: bd_name
      MYSQL_USER: kali
      MYSQL_PASSWORD: kali
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_network 

networks:
  custom_network:
    driver: bridge

volumes:
  db_data: